version: '3.8'
services:
  webapp:
    image: wc2182/webapp:v4
    ports:
      - "8000:5000"
    depends_on:
      - mongodb
    networks:
      - webnet

  mongodb:
    image: wc2182/mongodb:v5
    volumes:
      - mongodb_data:/data/db
    networks:
      - webnet

networks:
  webnet:

volumes:
  mongodb_data:
