version: '3.8'
services:
  webapp:
    image: wc2182/webapp:v4
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:123456@mongodb:27017/database
    networks:
      - webnet

  mongodb:
    image: wc2182/mongodb:v5
    volumes:
      - mongodb_data:/data/db
    networks:
      - webnet

networks:
  webnet:

volumes:
  mongodb_data:
