name: Webapp CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
    paths:
      - 'webapp/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'webapp/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./webapp
        file: ./webapp/Dockerfile
        push: true
        tags: yourusername/webapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - name: Deploy to Digital Ocean
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        # Commands to deploy your application to Digital Ocean
        # Example: doctl kubernetes cluster kubeconfig save <cluster-name>
        #          kubectl set image deployment/webapp webapp=yourusername/webapp:latest

